config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :orders
      resources :order_items
      resources :order_statuses
      resources :products

      root to: "orders#index"
    end
  resources :charges
  resources :products, only: [:index, :show]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items, dependent: :destroy
  before_save :update_subtotal

  def subtotal
    order_items.includes(:product).collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
private

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders, dependent: :destroy
end

app/models/product.rb
require 'uploads'

class Product < ApplicationRecord
  has_many :order_items
  has_one_attached :image

  default_scope { where(active: true) }

  def image_header_variant
    variation =
      ActiveStorage::Variation.new(Uploads.resize_to_limit(width: 500, height: -1, blob: image.blob))
    ActiveStorage::Variant.new(image.blob, variation)
  end

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    # before_action :authenticate_admin

    # def authenticate_admin
    #   # TODO Add authentication logic here.
    # end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    http_basic_authenticate_with(
      name: "omz",
      password: "mysecret"
    )
  end
end

app/controllers/admin/order_items_controller.rb
module Admin
  class OrderItemsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = OrderItem.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   OrderItem.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/order_statuses_controller.rb
module Admin
  class OrderStatusesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = OrderStatus.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   OrderStatus.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Order.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Order.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id].nil?
      Order.new
    else
      begin
        Order.find(session[:order_id])
      rescue ActiveRecord::RecordNotFound => e
        Order.new
      end
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items.includes(:product)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end
    
    def create
      # Amount in cents
      @amount = current_order.subtotal
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => (@amount * 100).to_i,
        :description => 'Wangoon Stripe customer',
        :currency    => 'usd'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order.order_items.new(order_item_params) do
      @order.order_status_id = 1
    end
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private

  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(image_attachment: :blob)
    #@order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/_cart_row.html.erb
<div class="card">
    <div class="row">
      <div class="col">
        <h4><%= product.name %></h4>
      </div>
      <div class="col">
        
        <%= form_for order_item, remote: true do |f| %>
          <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
          <div class="row">
            <div class="col">
              <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
              <%= f.hidden_field :product_id, value: product.id %>
            </div>
            <div class="col text-right">
              <div class="btn-group">
                <%= f.submit "Update Quantity", class: "btn btn-primary" %>
                <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
              </div>
            </div>
          </div>
          <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
        <% end %>
      </div>
      
    </div>
  </div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %> 
<% if @order_items.size == 0 %>
<p class="text-center">
  There are no items in your shopping cart. Please <%= link_to "go back",
  root_path %> and add some items to your cart.
</p>
<% else %> 
  <div class="container">
      <% @order_items.each do |order_item| %> 
      <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %> 
    <% end%> 
    <%= render "charges/new" %>
  </div>

<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart"><%= render "shopping_cart" %></div>

app/views/charges/_new.html.erb
<%= form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="A month's subscription"
        data-amount="<%= current_order.subtotal * 100 %>"
        data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @amount %></strong>!</h2>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer class="container">
  <p>
    &copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot;
    <a href="#">Terms</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <%= link_to "Wangoon", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Sell <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Today's Deals</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Gift Cards</a>
          </li>
        </ul>
        <span class="cart-text"><%= render 'layouts/cart_text' %></span>
      </div>
    </nav>
  </header>

app/views/layouts/_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "slide2.jpg", class:"img-fluid" %>
      <!--
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>Example headline.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
          </div>
        </div>
      -->
    </div>
    <div class="carousel-item">
      <%= image_tag "slide3.jpg", class:"img-fluid" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "slide4.jpg", class:"img-fluid" %>
    </div>
  </div>
  <a
    class="carousel-control-prev"
    href="#myCarousel"
    role="button"
    data-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a
    class="carousel-control-next"
    href="#myCarousel"
    role="button"
    data-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main role="main">
      <%= yield %>
    </main>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? %>
  alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
    <div class="col-lg-3 col-md-6 mb-4">
      <%= link_to product, class: "card" do %>
        <%= image_tag product.image.variant(resize_to_fill: [192, 192]), class: "card-img-top" %>
          <div class="card-body">
            <p class="card-text"><%= product.name %></p>   
          </div>
          <div class="card-footer text-muted">
              <p class="card-text">Price: <%= product.price %></p>
          </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%= render "product_row" %>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="card">
      <%= image_tag @product.image, class: "img-fluid" %>
      <div class="card-body">
        <h5 class="card-title"><%= @product.name %></h5>
        <%= form_for @order_item, remote: true do |f| %>
        <h4 class="text-right">
          Unit Price:
          <span style="color: green"><%= number_to_currency @product.price %></span>
        </h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1
          %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: @product.id %> <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>